### ISSUE TITLE
Descriptions and notes fields too small for NPC sheet

### ISSUE THREAD

**Issue by kdmcdrm** [Dez384/foundryvtt-blades-in-the-dark#11]
I might be misunderstanding how to use these, but the description and notes fields are quite small, which keep me from using those sheets at all.
I'd like the players to be able to track interactions with NPCs, previous deals etc in the Notes section.

**Comment by Dez384** [comment]
The notes section of the NPC sheet isn’t intended for long form note-taking. That would more purposefully be appropriate for a journal entry.

**Comment by Dez384** [comment]
The next release will have the "Full Description" and "Notes" sections of the NPC sheet as resizable text areas. This is currently live on the `Dev-5.2` branch.

**Comment by kdmcdrm** [comment]
Excellent, thanks so much for maintaining this.

**Comment by Dez384** [comment]
Completed with release [v5.2.0](https://github.com/Dez384/foundryvtt-blades-in-the-dark/releases/tag/v5.2.0)
