### ISSUE TITLE
Factions Tokens out of sync

### ISSUE THREAD

**Issue by kdmcdrm** [Dez384/foundryvtt-blades-in-the-dark#12]
I might be misunderstanding something here, but I pulled the Factions actor onto a scene and then modified it, but those changes are not reflected when I create that token in a new scene, ie it doesn't look like it updates the Actor's sheet.

From playing with it a little more, it does seem like the actor (in the menu on the right) does update the token on the scene, but not the other way around.

(Also I'd love to be able to set the actor's image for factions)

**Comment by Dez384** [comment]
By editing the Prototype Token for the actor, you can enable Actor Link. This will cause future tokens made to have their changes update the actor.

The next release will have Actor Link enabled by default for Faction Status actors. Additionally, the Faction Status sheet will have the ability to change the portrait and name of the actor. This is currently live on the `Dev-5.2` branch.

**Comment by Dez384** [comment]
Completed with release [v5.2.0](https://github.com/Dez384/foundryvtt-blades-in-the-dark/releases/tag/v5.2.0)
