### ISSUE TITLE
Rolling for Stress Relief uses wrong result

### ISSUE THREAD

**Issue by Thump92** [Dez384/foundryvtt-blades-in-the-dark#18]
Stress Relief should use the higher of two dice. The result in chat says it uses the lowest.

**Comment by Dez384** [comment]
When rolling dice, if "0d" is selected, the game system will roll 2d6 and keep the lowest. If "2d" is selected, then the game system will roll 2d6 and keep the highest. If an actor is selected, the game system can detect what the current stress of an actor is, but it does not currently choose the correct number of dice to roll. The number of dice must be input manually.

Using the simple roller, I rolled both 0d6 and 2d6 with the "Indulge Vice" option selected and it functioned as normal. This issue could not be replicated.
