### ISSUE TITLE
NPC Sheet adds whitespace characters to multiple fields when closing the form.

### ISSUE THREAD

**Issue by EffEssEmm** [Dez384/foundryvtt-blades-in-the-dark#20]
Input fields for "system.description_short", "system.associated_crew_type", and "system.associated_class" add whitespace to the end of entered strings every time the form is closed. This breaks certain things like crew NPC imports, and anything else that relies on exact matches to these attributes, if the player is viewing or editing NPCs. 

This appears to be caused by an extra character added to the end of lines 11, 16, and 26, inside the quotations at value attribution.

**Comment by Dez384** [comment]
Fixed in v5.3.2 release.
