### ISSUE TITLE
"Acquire Assets" roll is programmed incorrectly

### ISSUE THREAD

**Issue by linxcat** [Dez384/foundryvtt-blades-in-the-dark#21]
Acquire an Asset uses the crew tier as the dice pool. The dropdown is correctly coded to pull the tier of the crew attached to the selected token, but then it still rolls the number of dice manually specified at the top of the modal. Simply swap the value passed to the subsequent roll from one dropdown to the other.

**Comment by Dez384** [comment]
Fixed in v5.3.2 release.
