### ISSUE TITLE
Roll some Dice! UI doesn't inherit stats from selected token

### ISSUE THREAD

**Issue by linxcat** [Dez384/foundryvtt-blades-in-the-dark#4]
The "Roll Some Dice!" UI indicates that if you want to pull values from a character, one should select their token first. This doesn't appear to work, as the dropdowns always stay at zero, and it's not like the functionality simply transparent - it actually rolls a zero dice check.

**Comment by Dez384** [comment]
The Dice Roll Menu is not set up to pull from the token as that line of text suggests. That text will be removed in a future update.

**Comment by linxcat** [comment]
Got it, will remove locally through html in the mean time.

**Comment by linxcat** [comment]
@Dez384 My PR also removes the lang references. Ninja'd mne on the timing though! Sorry. #6

**Comment by Dez384** [comment]
This issue ended up being addressed in version 5.3.0. Having a token selected will pre-populate the tier and stress fields in the dice roller.
