### ISSUE TITLE
Fortune Roll / Engagement Roll

### ISSUE THREAD

**Issue by eaganlai** [Dez384/foundryvtt-blades-in-the-dark#5]
Sorry for being dumb. Where can I make a Fortune Roll / Engagement Roll?

**Comment by Dez384** [comment]
![Screenshot 2024-06-08 180734](https://github.com/Dez384/foundryvtt-blades-in-the-dark/assets/164457313/45e82318-151f-455e-b0fd-64c3e9efe0f3)

1. Select the Dice Roller on the left side of the screen
2. Choose what sort of roll to make (Engagement, Fortune, etc.)
3. Click the "Roll" button
