### ISSUE TITLE
Can't add turf manually

### ISSUE THREAD

**Issue by Lachrimae93** [Dez384/foundryvtt-blades-in-the-dark#8]
Hi, I recently found that there's no way to add turn manually without going through the claims map. According to the core book, turf can be gained without going through that map with a maximum of 6 total. Would appreciate if this could be fixed

**Comment by Dez384** [comment]
This issue has been addressed in the [5.2 development branch](https://github.com/Dez384/foundryvtt-blades-in-the-dark/tree/dev-5.2). 

Using active effects (either directly on the crew or attached to an item), create an effect that to `system.add_turf` `add` `1` or whatever number you want to add. The maximum turf is hardcoded at 6.

I will leave this issue open until I publish the change to the master branch. Implementation may alter as I continue to work through on the next development changes.

**Comment by Dez384** [comment]
I decided to refine the process a little more so the instructions in the previous comment won't work in the latest version on the development branch. 

1. To add additional turf, use an active effect to add to  `system.turf.bonus`
2. To change the maximum number of turf possible for a crew, use an active effect to alter `system.turf.max`

**Comment by Dez384** [comment]
Completed with release [v5.2.0](https://github.com/Dez384/foundryvtt-blades-in-the-dark/releases/tag/v5.2.0)
